### ISSUE TITLE
Problemas para gerar o guia completo

### ISSUE THREAD

**Issue by rgcavalcanti** [helioloureiro/guiafocalinux#4]
Bom dia!

Estou tendo problemas para gerar o guia com todas as versões (iniciante, intermediário e avançado). Segui o passo a passo descrito no README.md, mas gera somente o pdf com o nivel inciante.
Poderia me informar como faço para gerar o pdf completo?

Desde já obrigado!

**Comment by helioloureiro** [comment]
Não tenho idéia como o Gleydson gera o documento com as tags de iniciante, intermediário e avançado.  Devia ser algum parâmetro do docbook que sumiu com o passar dos anos.

Vou ver se arrumo pra gerar o avançado.

**Comment by helioloureiro** [comment]
Removi os iniciante/intermediário/avançado e agora ele gera completo.
