### ISSUE TITLE
Este guia se encontra em que estado atualmente?

### ISSUE THREAD

**Issue by DyeffersonAz** [helioloureiro/guiafocalinux#7]
Por mais que o básico início esteja atualizado, como se encontra este guia para 2019/2020?
É perda de tempo aprender por ele? Existe ainda o processo de atualizar este guia?

**Comment by helioloureiro** [comment]
Conforme vai aparecendo contribuições nós vamos atualizando.  Mas confesso que eu mesmo estou bem parado.  Talvez aproveite esse seu open issue pra atualizar alguma coisa.

**Comment by gnumoksha** [comment]
@DyeffersonAz o guia foca publicou uma atualizaçao há poucos dias https://guiafoca.org/?cat=60
